for l in [1, 2, 3, 4]: print(l ** 2, end=' ')
print('\n')
for t in (1, 2, 3, 4): print(t ** 3, end=' ')
print('\n')
for s in 'spam': print(s.upper(), end='.')
print('\n')
# Iterators
print('\n\t Iterations')
f = open('Cycles.py')
print(f.readline(), end='')
print(f.readline(), end='')
print(f.__next__(), end='')
print(f.__next__(), end='')
print(next(f), end='')
print(next(f), end='')
print()
print("Scan file with WHILE:")
f = open("ConsoleIO.py")
while 1:
    line = f.readline();
    if not line: break
    print(line.upper(), end=' ')
print('\n')
# iterators to dict
D = dict(a=1, b=2, c=3)
print(D)
K = D.keys()
print(K)
print(list(K))
V = D.values()
print(list(V))
print(list(D.items()))
I = iter(D)
print(next(I))
print(next(I))
print(next(I))
for key in D: print(key, end=' ')
print('\n')
for k in sorted(D.keys()):print(k,D[k],end=' ')
print('\n')
for k in sorted(D):print(k,D[k],end=' ')